spring:
  profiles:
    group:
      "real1": "real1_port"
      "real2": "real2_port"

---
spring:
  config:
    activate:
      on-profile: "real1_port"

server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: "real2_port"

server:
  port: 8082